services:
  aerospike:
    image: aerospike/aerospike-server-enterprise:7.0.0.2
    ports:
      - "3000:3000"
    networks:
      - avs-demo
    volumes:
      - ./container-volumes/aerospike/etc/aerospike:/opt/aerospike/etc/aerospike
    command:
      - "--config-file"
      - "/opt/aerospike/etc/aerospike/aerospike.conf"
      # use this line to store all index and vector data in the default namespace (test)
      # - "/opt/aerospike/etc/aerospike/aerospike-single-namespace.conf"
    healthcheck:
      test: [ "CMD", "asinfo", "-p", "3000", "-v", "build" ]
      interval: 5s
      timeout: 20s
      retries: 10
  avs:
    image: aerospike/aerospike-vector-search:0.9.0
    depends_on:
      aerospike:
        condition: service_healthy
    networks:
      - avs-demo
    volumes:
      - ./container-volumes/avs/etc/aerospike-vector-search:/etc/aerospike-vector-search
    healthcheck:
      test: ["CMD", "curl", "-f", "http://avs:5040/manage/rest/v1"]
      interval: 5s
      timeout: 20s
      retries: 10
  app:
    build:
      dockerfile: Dockerfile-prism
    depends_on: 
      avs:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - avs-demo
    environment:
      AVS_HOST: avs
      AVS_PORT: "5050"
      APP_NUM_QUOTES: "5000"
      GRPC_DNS_RESOLVER: native
    volumes:
      - ./container-volumes/prism/images:/prism/static/images/data

networks:
  avs-demo: {}
