version: "3.9"
services:
  aerospike-cluster:
    image: aerospike/aerospike-server-enterprise:7.0.0.5
    container_name: "aerospike-cluster"
    command: --config-file /etc/aerospike/aerospike.conf
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/config:/etc/aerospike
    healthcheck:
      test: [ "CMD", "asinfo", "-p", "3000", "-v", "build" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - svc
  aerospike-vector-search:
    image: aerospike/aerospike-vector-search:0.9.0
    container_name: "aerospike-vector-search"
    depends_on:
      aerospike-cluster:
        condition: service_healthy
    ports:
     - "5050:5050"
     - "5040:5040"
    networks:
      - svc
    volumes:
      - ${PWD}/config:/etc/aerospike-vector-search
    healthcheck:
      test: ["CMD", "curl", "-f", "http://aerospike-vector-search:5040/manage/rest/v1"]
      interval: 30s
      timeout: 20s
      retries: 3
networks:
  svc:
    name: svc


